# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	{ on = "l", run = 'plugin smart-enter' },
	{ on = "S", run = 'shell "$SHELL" --block --confirm' },
	{ on = [
		"'",
		"a",
	], run = "plugin yamb save", desc = "Add bookmark" },
	{ on = [
		"'",
		"'",
	], run = "plugin yamb jump_by_fzf", desc = "Jump bookmark by fzf" },
	{ on = [
		"'",
		"r",
	], run = "plugin yamb delete_by_key", desc = "Delete bookmark by key" },
	{ on = [
		"P",
	], run = "spot", desc = "Open spotter" },
	{ on = [
		"c",
		"a",
	], run = "plugin compress", desc = "Archive selected files" },
]

