[colors]
foreground=e0def4 # Text
background=191724 # Base
regular0=26233a   # Subtext 1
regular1=eb6f92   # red
regular2=31748f   # green
regular3=f6c177   # yellow
regular4=9ccfd8   # blue
regular5=c4a7e7   # pink
regular6=ebbcba   # teal
regular7=e0def4   # Surface 2
bright0=6c6f85    # Subtext 0
bright1=eb6f92    # red
bright2=31748f    # green
bright3=f6c177    # yellow
bright4=9ccfd8    # blue
bright5=c4a7e7    # pink
bright6=ebbcba    # teal
bright7=e0def4    # Surface 1
