#!/bin/bash

CONFIG="$HOME/.config/hypr/rofi/config.rasi"
#STYLE="$HOME/.config/hypr/wofi/style.css"
#COLORS="$HOME/.config/hypr/wofi/colors"

if [[ ! $(pidof rofi) ]]; then
	rofi -show drun -config ${CONFIG}
else
	pkill rofi
fi
