#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done
# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Xauthority
${SCRIPTSDIR}/xauthority &
